### ISSUE TITLE
哈喽

### ISSUE THREAD

**Issue by tang-zhonghua** [ChunjingXiao/DeepSeg#1]
你好 ， 有发表的论文链接吗？

**Comment by tang-zhonghua** [comment]
还有，数据集什么时候能够公布啊？

**Comment by ChunjingXiao** [comment]
The data can be downloaded now. Please get the URLs in 01CsiDataSet\Data_Download_Urls.txt.

Our paper is under review. Once it is accepted, we will update it.

**Comment by tang-zhonghua** [comment]
thank you!
